import streamlit as st
import utils

st.set_page_config(page_title="AI Insights", page_icon="🤖", layout="wide")

if 'df_enhanced' not in st.session_state:
    st.warning("Please go to the Home page to load the data first.")
    st.stop()

df = st.session_state['df_enhanced']
models = st.session_state['models']

st.header("🤖 AI-Powered Insights")
st.write("This section provides automated insights generated by analyzing the entire dataset and machine learning model performance.")

insights = utils.generate_insights(df)

if 'outcome_model' in models:
    model, le, accuracy, _ = models['outcome_model']
    st.markdown(f"""
    <div class="insight-box">
        <h4>Game Outcome Prediction Model</h4>
        <p>The AI model trained to predict whether a game is a 'Win' or 'Loss' based on player stats achieves <strong>{accuracy:.1%} accuracy</strong> on unseen test data. This indicates a strong relationship between in-game performance metrics and the final outcome.</p>
    </div>
    """, unsafe_allow_html=True)

for insight in insights:
    st.markdown(f"""
    <div class="insight-box">
        <p>{insight}</p>
    </div>
    """, unsafe_allow_html=True)