import streamlit as st
import utils 

# --- State Management and Sidebar ---
st.set_page_config(page_title="AI Insights", page_icon="🤖", layout="wide")
st.markdown(utils.load_css(), unsafe_allow_html=True)
utils.add_sidebar() 

# The definitive check: reload if data is missing.
utils.main_data_loader()

# Final check for data loading before page content
if 'df_enhanced' not in st.session_state or st.session_state.df_enhanced is None:
    st.warning("Data could not be loaded. Please select a valid worksheet from the sidebar.")
    st.stop()

# Get the dataframe and models from session state
df = st.session_state.df_enhanced
models = st.session_state.models

# --- Page Content ---
st.header("🤖 AI-Powered Insights")
st.write(f"This section provides automated insights generated by analyzing the **{st.session_state.loaded_sheet}** dataset.")

insights = utils.generate_insights(df)

if 'outcome_model' in models:
    model, le, accuracy, _ = models['outcome_model']
    st.markdown(f"""
    <div class="insight-box">
        <h4>Game Outcome Prediction Model</h4>
        <p>The AI model trained to predict whether a game is a 'Win' or 'Loss' based on player stats achieves <strong>{accuracy:.1%} accuracy</strong> on unseen test data. This indicates a strong relationship between in-game performance metrics and the final outcome.</p>
    </div>
    """, unsafe_allow_html=True)

for insight in insights:
    st.markdown(f"""
    <div class="insight-box">
        <p>{insight}</p>
    </div>
    """, unsafe_allow_html=True)