import streamlit as st
import utils # Make sure utils is imported

# Add the sidebar to the page and get the selected sheet
selected_sheet = utils.add_sidebar()

# --- Data Loading and State Management ---
# Check if data is loaded
if 'df_enhanced' not in st.session_state or not st.session_state.data_loaded:
    st.warning("Data not loaded. Please go to the Home page to load data.")
    st.stop()

# Check if the selected sheet in the sidebar is the one that's loaded
if st.session_state.get('loaded_sheet') != selected_sheet:
    st.warning(f"You selected the '{selected_sheet}' worksheet, but the '{st.session_state.get('loaded_sheet')}' worksheet is loaded. Please go to the Home page to load the new sheet.")
    st.stop()

# Get the dataframe from session state
df = st.session_state['df_enhanced']
models = st.session_state['models']
st.header("🤖 AI-Powered Insights")
st.write("This section provides automated insights generated by analyzing the entire dataset and machine learning model performance.")

insights = utils.generate_insights(df)

if 'outcome_model' in models:
    model, le, accuracy, _ = models['outcome_model']
    st.markdown(f"""
    <div class="insight-box">
        <h4>Game Outcome Prediction Model</h4>
        <p>The AI model trained to predict whether a game is a 'Win' or 'Loss' based on player stats achieves <strong>{accuracy:.1%} accuracy</strong> on unseen test data. This indicates a strong relationship between in-game performance metrics and the final outcome.</p>
    </div>
    """, unsafe_allow_html=True)

for insight in insights:
    st.markdown(f"""
    <div class="insight-box">
        <p>{insight}</p>
    </div>
    """, unsafe_allow_html=True)